### ISSUE TITLE
How to run CREATE TABLE queries? (run and query methods fail)

### ISSUE THREAD

**Issue by k00ni** [paragonie/easydb#75] opened 2018-04-03 08:15 UTC
I have the following setup:

```php
$db = Factory::create('sqlite:memory.db');
$db->run($sql);
// respectively
$db->query($sql);
```

The following CREATE TABLE query:

```sql
CREATE TABLE IF NOT EXISTS predicate (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    value   TEXT,
    UNIQUE(value)
);
```

fails to run using `run` and `query` method.

### run method

Error:
```bash
TypeError: Argument 1 passed to ParagonIE\EasyDB\EasyDB::getResultsStrictTyped() 
must be an instance of PDOStatement, boolean given, called in 
.../vendor/paragonie/easydb/src/EasyDB.php on line 759

.../vendor/paragonie/easydb/src/EasyDB.php:1042
...vendor/paragonie/easydb/src/EasyDB.php:759
.../vendor/paragonie/easydb/src/EasyDB.php:722
.../Adapter/SQliteMemory/Store.php:81
.../Adapter/SQliteMemory/StoreTest.php:14
```

### query method

```bash
TypeError: Return value of ParagonIE\EasyDB\EasyDB::query() must be an instance of 
PDOStatement, boolean returned

.../vendor/paragonie/easydb/src/EasyDB.php:1197
.../src/beardfulldb/Adapter/SQliteMemory/Store.php:81
```

What did i wrong?

**Comment by paragonie-scott** [comment] 2018-04-03 13:09
What version are you running?

**Comment by shadowhand** [comment] 2018-04-03 13:11
Most PDO statements return `false` on failure. Seems likely your SQL has an error.

**Comment by TUSIDENG** [comment] 2018-04-03 13:19
"AUTOINCREMENT" should be "AUTO_INCREMENT".

**Comment by paragonie-scott** [comment] 2018-04-03 13:27
The reason I'm perplexed is that we should be [throwing exceptions, not returning false, on failure](https://github.com/paragonie/easydb/blob/f35bd24abb31fa5a42a18b82fc26122d7c2fe931/src/EasyDB.php#L51-L54).

**Comment by k00ni** [comment] 2018-04-03 13:43
> "AUTOINCREMENT" should be "AUTO_INCREMENT".

I am using SQLite, therefore AUTOINCREMENT is correct, see [1].

[1] - https://sqlite.org/autoinc.html

**Comment by Nenglish7** [comment] 2018-04-04 02:44
your query should be.
```php
CREATE TABLE IF NOT EXISTS predicate (
id INTEGER PRIMARY KEY AUTOINCREMENT,
value TEXT,
UNIQUE(value))
```
Excluding the `;`.
I look at some examples here <https://www.if-not-true-then-false.com/2012/php-pdo-sqlite3-example/>.

**Comment by TUSIDENG** [comment] 2018-04-04 05:12
@k00ni Yes, You are right.I'm a novice.I know a little about SQLite, I use 'ATUO_INCREMENT' in mysql.I learned new knowledeg because of your reply.Thanks.

**Comment by k00ni** [comment] 2018-04-04 06:59
> your query should be.

I just saw that my query didnt has the `;` at the end. But it doesn't seem to be a problem, according to this Stackoverflow [answer](https://stackoverflow.com/questions/13202600/android-and-sqlite-when-to-use-semicolons-to-end-statements/13202636#13202636).

Either way, the result is the same. I can run them using PDO directly via `exec`. But not with EasyDB.

**Comment by fredricj** [comment] 2018-04-04 07:37
Can you post a self-contained example showing the problem? The following code based your code above works fine on easydb 2.6.0 and php 7.1 
```
<?php
require_once(__DIR__.'/../vendor/autoload.php');

$sql = "CREATE TABLE IF NOT EXISTS predicate (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    value   TEXT,
    UNIQUE(value)
);";
$db = \ParagonIE\EasyDB\Factory::create('sqlite:memory.db');
$db->run($sql);
```

**Comment by k00ni** [comment] 2018-04-04 08:06
> Can you post a self-contained example showing the problem?

Sure.

Failing PHP code:

```php
$db = \ParagonIE\EasyDB\Factory::create('sqlite::memory:');

$tables = explode(';', file_get_contents(__DIR__.'/tables.sql'));

foreach ($tables as $sql) {
    $res = $db->run($sql); // <==== throws the error
}
```

Related `tables.sql`:

```sql
CREATE TABLE IF NOT EXISTS quad (
    graph           INTEGER NOT NULL,
    subject         INTEGER NOT NULL,
    predicate       INTEGER NOT NULL,
    object          INTEGER NOT NULL,
    PRIMARY KEY (graph, subject, predicate, object)
);

CREATE TABLE IF NOT EXISTS graph (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    value   TEXT,
    UNIQUE(value)
);

CREATE TABLE IF NOT EXISTS subject (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    value   TEXT,
    type    TEXT CHECK(type in ('uri','bnode') ) NOT NULL default 0,
    UNIQUE(value)
);

CREATE TABLE IF NOT EXISTS predicate (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    value   TEXT,
    UNIQUE(value)
);

CREATE TABLE IF NOT EXISTS object (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    value       TEXT NOT NULL,
    datatype    TEXT,
    type        TEXT CHECK(type in ('uri', 'bnode', 'literal')) NOT NULL
);
```
It seems the last query (table `object`) is causing the problem, because without the fifth query no error is thrown.

I tried renaming it to `object1`, to exclude a reserved word problem, but no change. Also ran the same queries with:
* DB Browser for SQLite: no problems
* PDO directly using `$db->getPdo()->exec($sql)`: no problems

The following code runs without a problem:

```php
$db = \ParagonIE\EasyDB\Factory::create('sqlite::memory:');

$tables = explode(';', file_get_contents(__DIR__.'/tables.sql'));

foreach ($tables as $sql) {
    $res = $db->getPdo()->exec($sql); // <==== using PDO directly works fine
}
```

**Comment by fredricj** [comment] 2018-04-04 09:00
The problem is that the last query is basically an empty query: "\n" in which case PDO::query() returns false and the [code](https://github.com/paragonie/easydb/blob/f35bd24abb31fa5a42a18b82fc26122d7c2fe931/src/EasyDB.php#L755-L759) assumes it never will(?).
```
<?php
require_once(__DIR__.'/../vendor/autoload.php');
$sql = "";
$db = \ParagonIE\EasyDB\Factory::create('sqlite:memory');
$db->run($sql);
```

**Comment by k00ni** [comment] 2018-04-04 11:26
> The problem is that the last query is basically an empty query

Hi @fredricj, that really seems be the problem. Will try to confirm that in the next days. Thanks for the hint.

**Comment by Nenglish7** [comment] 2018-04-04 12:56
if your using memory thats wrong syntax.
`ParagonIE\EasyDB\Factory::create('sqlite:memory');` should be `ParagonIE\EasyDB\Factory::create('sqlite::memory:');`

- http://php.net/manual/en/ref.pdo-sqlite.connection.php

**Comment by k00ni** [comment] 2018-04-04 13:45
@Nenglish7 you are right, missed the `:` when preparing the example code.

**Comment by k00ni** [comment] 2018-05-29 15:42
Hi, sorry for the late response. I guess the problem was the empty query in the end. But as @paragonie-scott stated:

> The reason I'm perplexed is that we should be throwing exceptions, not returning false, on failure.

this fact is very confusing to me too. Could this be a problem?

**Comment by fredricj** [comment] 2018-05-30 08:52
> The problem is that the last query is basically an empty query: "\n" in which case PDO::query() returns false and the code assumes it never will(?).
> 
>     <?php
>     require_once(__DIR__.'/../vendor/autoload.php');
>     $sql = "";
>     $db = \ParagonIE\EasyDB\Factory::create('sqlite:memory');
>     $db->run($sql);
> 
> If your using memory thats wrong syntax.
> ParagonIE\EasyDB\Factory::create('sqlite:memory'); should be ParagonIE\EasyDB\Factory::create('sqlite::memory:');
> 
>     https://secure.php.net/manual/en/ref.pdo-sqlite.connection.php

Okay, I used the wrong syntax there so it creates a file instead, but it still show the issue with empty queries. I wrote a test case for PDO with both mysql and sqlite and they seem to handle it differently:
```php
<?php
$opt = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE =>PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
];

$pdo = new PDO("mysql:host=127.0.0.1;charset=utf8mb4", "test", "test", $opt);
#$pdo = new PDO("sqlite::memory:", null, null, $opt);

$stmt = $pdo->query("\n");
var_dump($stmt);
while($row = $stmt->fetch()) {
        print_r($row);
        echo "\n";
}
```
Mysql:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty in /home/fredric/t.php:11
Stack trace:
#0 /home/fredric/t.php(11): PDO->query('\n')
#1 {main}
  thrown in /home/fredric/t.php on line 11

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty in /home/fredric/t.php:11
Stack trace:
#0 /home/fredric/t.php(11): PDO->query('\n')
#1 {main}
  thrown in /home/fredric/t.php on line 11
```
sqlite:
```
bool(false)
PHP Fatal error:  Uncaught Error: Call to a member function fetch() on boolean in /home/fredric/t.php:13
Stack trace:
#0 {main}
  thrown in /home/fredric/t.php on line 13

Fatal error: Uncaught Error: Call to a member function fetch() on boolean in /home/fredric/t.php:13
Stack trace:
#0 {main}
  thrown in /home/fredric/t.php on line 13
```

**Comment by paragonie-scott** [comment] 2018-10-18 18:37
I think we should add a check when calling `prepare()` to ensure the query string isn't empty, then throw our own exception. That should prevent anyone from spending a lot of time on troubleshooting.

**Comment by paragonie-scott** [comment] 2018-11-28 17:34
This will be fixed in the next release. #94 contained the proposed fix.

**Closed by paragonie-scott** 2018-11-28 17:34 UTC

**Comment by jjokham** [comment] 2019-03-14 22:25
how can you run trigger queries. I get the following error. 
```
                         $triggerquery = " CREATE TRIGGER `$triggername` $triggertime ON `$tablename` 
							FOR EACH ROW 
							BEGIN 
								IF(NEW.`$triggercol` IS NULL) 
								THEN 
									SET NEW.`$triggercol` = UNIX_TIMESTAMP(); 
								END IF; 
							END;
						";
```
