### ISSUE TITLE
EasyStatement throws exception when the array is empty

### ISSUE THREAD

**Issue by kamil-tekiela** [paragonie/easydb#111] opened 2019-03-30 13:42 UTC
Sometimes there is a need to build complex WHERE clauses and building the EasyStatement conditionally is not very convenient. If the values array is null EasyStatement should not add that WHERE clause to the SQL instead of letting PHP dump about incorrect number of arguments.

Example:

    $dynamicArray = []; // Values are dynamically build somewhere else, but the array could also be empty
    EasyStatement::open()->in('`Id` IN (?*)', $dynamicArray);

The result of this will be:
>Warning: str_repeat(): Second argument has to be greater than or equal to 0 in ...EasyStatement.php on line 380

To avoid the exception I need to check if the array is empty before adding the next clause to EasyStatement

**Comment by shadowhand** [comment] 2019-03-30 18:38
> To avoid the exception I need to check if the array is empty before adding the next clause to EasyStatement

That is correct.

**Comment by paragonie-scott** [comment] 2019-04-22 16:15
@kamil-tekiela Does #113 look like it will make your life easier?

**Comment by kamil-tekiela** [comment] 2019-04-22 16:59
@paragonie-scott Yes, I downloaded that branch and tested it with my code, and it would solve my problem. 
I have one suggestion though. It is getting too verbose when you have to call this setter method for every new EasyStatement as well as all the groups inside. Could you maybe add it as a defaulted parameter into the `open` and `andGroup` methods? 

Instead of this:

	EasyStatement::open()->setEmptyInStatementsAllowed(true)->andGroup()->setEmptyInStatementsAllowed(true)

I would prefer this:

	EasyStatement::open(true)->andGroup(true)

**Comment by paragonie-scott** [comment] 2019-04-22 17:00
Oh, good catch. It should inherit.

**Comment by paragonie-scott** [comment] 2019-04-22 17:07
Okay, you now only need to call `EasyStatement::open()->setEmptyInStatementsAllowed(true)` and the groups will inherit this flag.

I'm going to keep the API for setting this flag explicit, rather than a magical boolean you have to look into the documentation to understand the purpose of.

**Comment by kamil-tekiela** [comment] 2019-04-22 17:24
One more thing I do not understand. Why did you add `AND 1=0` clause in the `orIn()` method?

**Comment by paragonie-scott** [comment] 2019-04-22 17:29
`EasyStatement` has no idea what database driver you're using, and by design, has *no way to figure that out*.

TRUE / FALSE have weird behavior in e.g. SQLite versus PostgreSQL. However, `1 = 0` always returns the correct falsy value (be it `0`, `FALSE`, or something else).

Similarly, `foo IN ()` is a syntax error. If you invoke `orIn([])` the correct thing to do is return false.

**Comment by kamil-tekiela** [comment] 2019-04-22 17:32
No. I meant that the OR condition could be just left empty. I do not see a need to have the fallback `AND 1=0` for the OR condition. I understand completely that `TRUE/FALSE` is not in every DB.

**Comment by paragonie-scott** [comment] 2019-04-22 17:32
Oh wait! Were you asking about an `AND`/`OR` confusion? That's a pasto.

**Comment by paragonie-scott** [comment] 2019-04-22 17:33
> No. I meant that the OR condition could be just left empty.

Agreed. https://github.com/paragonie/easydb/pull/113/commits/32e81d54a47129b3dbf441937d75ea8bc5a4ab23

**Comment by kamil-tekiela** [comment] 2019-04-22 17:36
Yes. That looks better. Thanks.

**Comment by paragonie-scott** [comment] 2019-08-15 00:44
We should be good to go on the next release. I'm just waiting to see if @SignpostMarv has any other changes to slate for `v2.10.0` before I tag it.

**Comment by SignpostMarv** [comment] 2019-08-15 10:38
@paragonie-scott just the thing on my to-do list, SignpostMarv/note-to-self#7, was thinking of adding methods `EasyDB::insertIgnore(string $table, array<string, scalar|null> $row)` & `EasyDB::insertOnDuplicateKeyUpdate(string $table, array<string, scalar|null> $row, array<int, key-of<$row>)`, but those could wait for the next release if you'd prefer ?

**Comment by paragonie-scott** [comment] 2019-08-15 23:00
Fixed in `v2.10.0`

**Closed by paragonie-scott** 2019-08-15 23:00 UTC
